spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    driver-class-name: ${DRIVER_CLASS}
    url: ${DB_URL}
    username: ${NAME}
    password: ${PASSWORD}

  jpa:
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
jwt:
  header: ${HEADER}
  secretKey: ${SECRET}
  accessExpiredAt: ${ACCESS}
  accessClaim: ${ACCESS_CLAIM}
  refreshExpiredAt: ${REFRESH}
  refreshClaim: ${REFRESH_CLAIM}